### ISSUE TITLE
게시글 댓글 응답 데이터 수정 요청

### ISSUE THREAD

**Issue by yerim425** [10000DOO/YouHaveTo#170]
1. 게시글 상세조회 응답 데이터 중 댓글 데이터의 commendId와 profileImage 멤버 값이 항상 null 값으로 오는데 수정 부탁드려요.
2. 부모 댓글 삭제 후 다시 조회하면, 삭제했던 부모 댓글이 그대로 오는데 수정 부탁드려요.
3. 자식 댓글 삭제 후 다시 조회하면, 자식 댓글은 삭제되었지만 부모 댓글의 childCount 값은 수정되지 않아요.

**Comment by 10000DOO** [comment]
수정했습니다.
